add update_and_fetch_row & update_and_emulate_row
karupanerura/Aniki pull request #16
Opened 2017-06-16 10:26 UTC by mamimumemoomoo

Fix: https://github.com/karupanerura/Aniki/issues/15

Please review PR

2017-06-17 07:17 UTC, karupanerura requested changes
Thank you for your patch. Good job! but, I found some problems of the code.
Please consider these points of view and please fix this patch.

2017-06-17 07:17 UTC, karupanerura commented on lib/Aniki.pm
> +        croak '(Aniki#update_and_fetch_row) condition must be a Aniki::Row object.';
It should check at first of the method for less nest of code.
`croak '...' if blessed $_[0] && $_[0]->isa('Aniki::Row');`

2017-06-17 07:17 UTC, karupanerura commented on lib/Aniki.pm
> +        return $row if $self->suppress_row_objects;
Please read doc about `suppress_row_objects`: https://metacpan.org/pod/Aniki#suppress_row_objects-:-Bool

2017-06-17 07:17 UTC, karupanerura commented on lib/Aniki.pm
> +        my $row = $self->select($_[0]->table_name, $self->_where_row_cond($_[0]->table, $_[0]->row_data), { limit => 1, suppress_result_objects => 1 })->[0];
It should follow changing value of primary key or it fetch other row.

2017-06-17 07:17 UTC, karupanerura commented on lib/Aniki.pm
> +    my $self = shift;
This method's arguments should be assign to obvious variable.

2017-06-17 07:17 UTC, karupanerura commented on lib/Aniki.pm
> +    my $self = shift;
ditto

2017-06-17 07:17 UTC, karupanerura commented on lib/Aniki.pm
> +        croak '(Aniki#update_and_emulate_row) condition must be a Aniki::Row object.';
ditto

2017-06-17 08:12 UTC, mihyaeru21 commented on lib/Aniki.pm
> +        croak '(Aniki#update_and_fetch_row) condition must be a Aniki::Row object.';
`croak '...' unless blessed $_[0] && $_[0]->isa('Aniki::Row');` ?

2017-06-17 08:14 UTC, karupanerura commented on lib/Aniki.pm
> +        croak '(Aniki#update_and_fetch_row) condition must be a Aniki::Row object.';
oops! that's right! thanks!

2017-06-19 02:51 UTC, mamimumemoomoo commented on lib/Aniki.pm
> +    my $self = shift;
fix d4c6564fe100f5a9638cfae9597eec7da87c8969

2017-06-19 02:52 UTC, mamimumemoomoo commented on lib/Aniki.pm
> +    my $self = shift;
d4c6564fe100f5a9638cfae9597eec7da87c8969

2017-06-19 02:52 UTC, mamimumemoomoo commented on lib/Aniki.pm
> +        croak '(Aniki#update_and_fetch_row) condition must be a Aniki::Row object.';
fix a6b8df1f9da2e39735f0e7351e0cafa57814b5c6

2017-06-19 02:53 UTC, mamimumemoomoo commented on lib/Aniki.pm
> +        croak '(Aniki#update_and_emulate_row) condition must be a Aniki::Row object.';
a6b8df1f9da2e39735f0e7351e0cafa57814b5c6

2017-06-19 02:56 UTC, mamimumemoomoo commented on lib/Aniki.pm
> +        return $row if $self->suppress_row_objects;
if suppress_row_objects is true, can not pass $row object.
Is my understanding correct?
64b13c451ff651bd9dc8cb9c1d0f7ce932f90914

2017-06-19 02:57 UTC, mamimumemoomoo commented on lib/Aniki.pm
> +        my $row = $self->select($_[0]->table_name, $self->_where_row_cond($_[0]->table, $_[0]->row_data), { limit => 1, suppress_result_objects => 1 })->[0];
oopus! 8ed502635921f6c1902bc17b0082ca09273957cf

2017-06-19 09:00 UTC, karupanerura commented on lib/Aniki.pm
> +        return $row if $self->suppress_row_objects;
Yes! That's right. so this is meaningless branch.

2017-06-19 09:01 UTC, karupanerura requested changes

2017-06-19 09:01 UTC, karupanerura commented on lib/Aniki.pm
> +    $row_data = $self->filter_on_update($row->table_name, $row_data);
please follow `suppress_row_objects` at here.

2017-06-19 09:02 UTC, karupanerura commented
@mamimumemoomoo Thank you. Please fix a point and I'll merge it.

2017-06-21 04:45 UTC, karupanerura commented
OK. I'll fix it. Good Job!

2017-06-21 04:45 UTC, karupanerura approved these changes

2017-06-21 04:45 UTC, merged

2017-06-21 07:02 UTC, karupanerura commented
@mamimumemoomoo Hi.
I've released this feature as 1.04_02 on CPAN (developer release).
Could you try it in your application?

2017-06-22 03:27 UTC, mamimumemoomoo commented
I'm sorry to reply late.
Thank you for support and review.
I'll try new version.

2017-06-29 07:26 UTC, karupanerura commented
@mamimumemoomoo How is the progress?
If there are no anxiety, I'll release it as new version.

2017-06-29 07:56 UTC, mamimumemoomoo commented
@karupanerura 
Thank you! We're on track for now.
I'm looking forward to it.

2017-07-14 06:12 UTC, karupanerura commented
released it as 1.05